ATF_POINT_IN_MM = 0.3514056
DIDOT_POINT_IN_MM = 0.3759

TRADITIONAL_NAMES = [
  ["excelsior", 3, :us],
  ["minikin", 3, :uk],
  ["brilliant", 4],
  ["diamond", 4.5],
  ["pearl", 5],
  ["agate", 5.5, :us],
  ["ruby", 5.5, :uk],
  ["nonpareille", 6],
  ["minionette", 6.5, :us],
  ["emerald", 6.5, :uk],
  ["minion", 7],
  ["small text", 8],
  ["petit", 8],
  ["brevier", 8],
  ["borgeois", 9],
  ["galliard", 9],
  ["long primer", 10],
  ["corpus", 10],
  ["garamond", 10],
  ["small pica", 11],
  ["philosophy", 11],
  ["pica", 12],
  ["english", 14],
  ["mittel", 14],
  ["augustin", 14],
  ["columbian", 16, :us],
  ["two-line brevier", 16, :uk],
  ["great primer", 18],
  ["paragon", 20],
  ["double small pica", 21, :uk],
  ["double small pica", 22, :us],
  ["double pica", 24, :us],
  ["two-line pica", 24, :uk],
  ["double english", 28, :us],
  ["two-line english", 28, :uk],
  ["five-line nonpareil", 30, :us],
  ["four-line brevier", 32, :us],
  ["double great primer", 36, :us],
  ["two-line great primer", 36, :uk],
  ["meridian", 44, :us],
  ["two-line double pica", 44, :uk],
  ["trafalgar", 44],
  ["canon", 48],
  ["four-line", 48],
  ["five-line pica", 60],
  ["inch", 72]
]